### ISSUE TITLE
hakyll org-mode metadata

### ISSUE THREAD

**Issue by xcaptain** [turboMaCk/turboMaCk.github.io#1]
I googled `hakyll org-mode` and found you blog, I'm also a hakyll org-mode user, but I hate markdown metadata format in org-mode, do you have any better solution?

markdown metadata:
```markdown
--- title: some title
-- author: author name
```

org-mode metadata
```org-mode
#+TITLE: some title
#+AUTHOR: author name
```

**Comment by turboMaCk** [comment]
Hi @xcaptain 👋 
yeah I know what you mean. I would also rather have org compatible meta. However beside trying it and realizing it doesn't work I didn't spent any time looking for possible solution. Let me know if you find something.

**Comment by xcaptain** [comment]
:sob: org-mode style metadata is not supported officially. haskell hakyll, emacs org-mode are not very popular for most people hope to see some people can fix this. ps: I'm learning haskell now :smiley:
