### ISSUE TITLE
Currently looking for new opportunities

### ISSUE THREAD

**Issue by Janiczek** [turboMaCk/turboMaCk.github.io#5]
https://github.com/turboMaCk/turboMaCk.github.io/blob/develop/index.html#L23
Perhaps not as accurate anymore :D

**Comment by turboMaCk** [comment]
:D yeah I know. I plan to update it soonish. There is always so many things to do :P

**Comment by turboMaCk** [comment]
I always wanted to say it so:
patch delivered directly to development branch https://github.com/turboMaCk/turboMaCk.github.io/commit/3ab6002466d6e7060705e88d5398ccef5fcada9f
