### ISSUE TITLE
Invalid link to other posts

### ISSUE THREAD

**Issue by bcardiff** [turboMaCk/turboMaCk.github.io#7]
I'm not sure why but the link in https://turbomack.github.io/posts/2020-05-12-anonymous-types-matter.html#so-why-anonymous-types-matter / https://github.com/turboMaCk/turboMaCk.github.io/blame/develop/posts/2020-05-12-anonymous-types-matter.org#L376

is rendered as

```
<p>
  Anonymous types fill certain needs in software design pretty well. 
  This goes back to the open/closed principles 
  <a href="file:///posts/2019-08-14-avoiding-pattern-matching-refunctionalization.html">
    I wrote about some time ago
  </a>.
</p>
```

instead of `/posts/2019-08-14-avoiding-pattern-matching-refunctionalization.html`

**Comment by turboMaCk** [comment]
Fixed in newest deployment
